# numpy Package - Example Answers

In [2]:
import numpy as np

## Create numpy arrays using numpy functions

Use the numpy arange function to create an array with integers from 1 to 9 inclusive.  Name this array1.

In [3]:
# Write your code here
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Use the numpy linspace function to create an array with 9 numbers, evenly spaced between 0 and 200.  Name this array2.

In [4]:
# Write your code here
array2 = np.linspace(0, 200, 9)
array2

array([  0.,  25.,  50.,  75., 100., 125., 150., 175., 200.])

## Operate  (calculate, reshape, filter) on numpy arrays

Multiply all elements of array1 by 10 

In [5]:
# Write your code here
array1 * 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Add each element of array1 to the corresponding element of array2.  The result should be also be a numpy array.

In [6]:
# Write your code here
array1 + array2

array([  1.,  27.,  53.,  79., 105., 131., 157., 183., 209.])

Create a new array, that has the elements of array1 but has 3 rows and 3 columns.

In [7]:
# Write your code here
array1.reshape([3, 3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Filter array1 to return an array of only the even numbers.  
Hint: you may want to use the fact that x % 2 == 0 is True for event numbers, False for odd

In [8]:
# Write your code here
array1[array1 % 2 == 0]

array([2, 4, 6, 8])

**Exercise : BMI**

Calculate the BMI of these three people.  The BMI is the weight (kg) divided by the height (metres) squared.

In [12]:
weights = [74, 75, 76]
heights = [1.77, 1.76, 1.75]

In [13]:
# Write your code here
weights_np = np.array(weights)
heights_np = np.array(heights)
weights_np / heights_np ** 2

array([23.62028791, 24.21229339, 24.81632653])


## Exercise: Football
The numpy arrays below contain the results (the number of matches won, drawn and lost) of five teams.  For example the first team has won four matches, drawn two and lost one.  Teams have played a different number of matches.

In [14]:
team_won = np.array([4, 3, 1, 6, 3])
team_drawn = np.array([2, 1, 1, 7, 2])
team_lost = np.array([1, 3, 4, 5, 8])

Create a numpy array, team_played, to hold the number of games played 


In [15]:
# Write your code here
team_played = team_won + team_drawn + team_lost
team_played

array([ 7,  7,  6, 18, 13])

Create a numpy array, team_score, to hold the teams scores (3 for a win, 1 for a draw, 0 for a loss)

In [16]:
# Write your code here
team_score = 3 * team_won + team_drawn
team_score

array([14, 10,  4, 25, 11])