# numpy Package

numpy is a very important package in Python. It provides the np.ndarray data type (array for short). Unlike lists, all the element in arrays must be the same data type (usually  ints or float). We can do element-wise operations on these arrays to make our code simpler & shorter.
Operatons on arrays work a lot faster than operations on lists.


In [2]:
import numpy as np

In [6]:
# Create numpy arrays
a = np.zeros(3) # initialise with all elements with value 0
b = np.ones(3) # # initialise with all elements with value 1
a, b, type(a), type(a[0])

(array([0., 0., 0.]), array([1., 1., 1.]), numpy.ndarray, numpy.float64)

In [8]:
# Create an numpy array from a list
np_squares = np.array([1, 4, 9, 16, 25])
np_squares, type(np_squares) 

(array([ 1,  4,  9, 16, 25]), numpy.ndarray)

In [9]:
# Create an numpy array  with a set of random values
a = np.random.randn(5) # standard normal distribution
b = np.random.randint(low = 100, high = 200, size = 6) # discrete, uniform distribution
a, b

(array([-1.52960732, -0.07574867, -0.15655135, -0.62838012,  0.31657364]),
 array([154, 105, 161, 158, 144, 115]))

In [10]:
# Examine numpy arrays
np_squares.shape # This array has one dimension

(5,)

In [16]:
#  A numpy array can also be 2 or more dimensions
list_of_lists = [[1,2,3], [4,5,6]]
a2 = np.array(list_of_lists) # from a list of lists
a2.shape, a2.ndim # 2 dimensions

((2, 3), 2)

In [17]:
a2 = np.random.randn(4, 3) 
a2, a2.shape

(array([[ 1.03908929,  1.43154874, -0.67012927],
        [-0.09570645,  0.59901196,  1.4657608 ],
        [ 0.64719777, -0.38611462,  1.63005971],
        [-1.72268592,  0.91067423, -0.30783799]]),
 (4, 3))

## Operate on numpy arrays
We can take advantage of element-wise operations. We don't need to loop through the elements of the array.

In [18]:
#  Add (or multiply...) a constant value to each element in the array
np_squares + 10

array([11, 14, 19, 26, 35])

In [19]:
#  Add (or multiply...)  two arrays
a = np.array([3,4,5])
b = np.array([30,40,50])
a + b

array([33, 44, 55])

## Filter arrays

In [23]:
np_squares < 15 # return an array of booleans the same length as the array

array([ True,  True,  True, False, False])

In [24]:
np_squares[np_squares < 15] # returns a smaller array with only those elements that meet the criteria

array([1, 4, 9])

### Exercise : calculate the BMI of these three people
The BMI is the weight divided by the height squared


In [25]:
weights = [74, 75, 76]
heights = [1.77, 1.76, 1.75]

w = np.array(weights)
h = np.array(heights)
def bmi(weight, height):
    """
    Returns the body mass index of a person given the weight (kg) and height(m) 
    """
    return weight / (height * height)

bmi(w, h)

array([23.62028791, 24.21229339, 24.81632653])


### Exercise:
The numpy arrays below contain the results (the number of matches won, drawn and lost) of five teams

1. Create a numpy array, team_played, to hold the number of games played 
2. Create a numpy array, team_score, to hold the teams scores (3 for a win, 1 for a draw, 0 for a loss)

In [ ]:
team_won = np.array([4, 3, 1, 6, 3])
team_drawn = np.array([2, 1, 1, 7, 2])
team_lost = np.array([1, 3, 4, 5, 8])

### Exercise: calculate the family size for each of these passengers
The Titanic dataset a row for each passengers and has two integer columns sib_sp and parch
To find the size of the family group. family_size, we add sib_sp to parch and add 1.
Let's look at the  7 passengers.


In [ ]:
titanic_sib_sp = [2, 0, 3, 1, 4, 0]
titanic_parch = [1, 2, 1, 1, 2, 3]


In [ ]:
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 


In [ ]:
# football
team_played = team_won + team_drawn + team_lost
team_score = 3 * team_won + team_drawn

# BMI
np_weights = np.array(weights)
np_heights = np.array(heights)
np_weights / (np_heights * 2)

# Titanic
titanic_sib_sp_np = np.array(titanic_sib_sp)
titanic_parch_np = np.array(titanic_parch)
titanic_family_size_np = titanic_parch_np + titanic_sib_sp_np + 1
