# Basics of the Numpy Package
Just enough numpy that we need to do our data analysis in pandas

numpy is a very important package in Python. It provides the np.ndarray data type (array for short). Unlike lists, all the element in arrays must be the same data type (usually  ints or float). We can do element-wise operations on these arrays to make our code simpler & shorter.
Operatons on arrays work a lot faster than operations on lists.


In [1]:
import numpy as np

In [2]:
# Create numpy arrays
a = np.zeros(3) # initialise with all elements with value 0
b = np.ones(3) # # initialise with all elements with value 1
a
type(a[0])


numpy.float64

In [3]:
# Create an numpy array from a list
np_squares = np.array([1, 4, 9, 16, 25])
type(np_squares) # a n-dimensional array
np_squares

array([ 1,  4,  9, 16, 25])

In [4]:
# Create an numpy array  with a set of random values
a = np.random.randn(5) # normal distribution
a = np.random.randint(low = 100, high = 200, size = 6) # discrete, uniform distribution
a

array([122, 106, 199, 148, 120, 107])

In [5]:
# Examine numpy arrays
np_squares.shape # This array has one dimension

(5,)

In [6]:
#  Aside: Array can also be 2  (or more) dimensions
list_of_lists = [[1,2,3], [4,5,6]]
a2 = np.array(list_of_lists) # from a list of lists
a2.shape

a2 = np.random.randn(5, 6) 
a2.shape

(5, 6)

## Operate on numpy arrays
Take advantage of element-wise operations


In [7]:
#  Add (or multiply...) a constant value to each element in the array
np_squares + 10

array([11, 14, 19, 26, 35])

In [8]:
#  Add (or multiply...)  two arrays
a = np.array([3,4,5])
b = np.array([30,40,50])
a + b

array([33, 44, 55])

In [9]:
# Filter arrays
np_squares < 15 # resturn an array of booleans the same length as the array
np_squares[np_squares < 15] # returns a smmaler array with only those elements that meet the criteria

array([1, 4, 9])

### Exercise : calculate the BMI of these three people
The BMI is the weight divided by the height squared


In [10]:
weights = [74, 75, 76]
heights = [1.77, 1.76, 1.75]

w = np.array(weights)
h = np.array(heights)
def bmi(height, weight):
    """
    Returns the body mass index of a person given the weight (kg) and height(m) 
    """
    return weight / (height * height)

bmi(h, w)

array([23.62028791, 24.21229339, 24.81632653])


### Exercise:
The numpy arrays below contain the results (the number of matches won, drawn and lost) of five teams

1. Create a numpy array, team_played, to hold the number of games played 
2. Create a numpy array, team_score, to hold the teams scores (3 for a win, 1 for a draw, 0 for a loss)

In [11]:
team_won = np.array([4, 3, 1, 6, 3])
team_drawn = np.array([2, 1, 1, 7, 2])
team_lost = np.array([1, 3, 4, 5, 8])

### Exercise: calculate the family size for each of these passengers
The Titanic dataset a row for each passengers and has two integer columns sib_sp and parch
To find the size of the family group. family_size, we add sib_sp to parch and add 1.
Let's look at the  7 passengers.


In [12]:
titanic_sib_sp = [2, 0, 3, 1, 4, 0]
titanic_parch = [1, 2, 1, 1, 2, 3]


In [ ]:
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 
# EXERCISE ANSWERS 


In [13]:
# football
team_played = team_won + team_drawn + team_lost
team_score = 3 * team_won + team_drawn

# BMI
np_weights = np.array(weights)
np_heights = np.array(heights)
np_weights / (np_heights * 2)

# Titanic
titanic_sib_sp_np = np.array(titanic_sib_sp)
titanic_parch_np = np.array(titanic_parch)
titanic_family_size_np = titanic_parch_np + titanic_sib_sp_np + 1
