# numpy Package - Example Answers

In [3]:
import numpy as np

**Exercise: Titanic**

These lists represents 7 passengers from the Titanic.  For example, the first passenger has 2 sibling/spouses and one parent/child. Calculate the family size for each passenger.  To do this, add sib_sp (the number of siblings and spouses) to parch (the number of parents and children) and add 1 (for the passenger).

You can choose to do this either using numpy or not.  With the numpy approach, firstly convert the lists to numpy arrays.  In the other approach you may want to zip the lists together then use in a list comprehension to do the calculation.

In [1]:
sib_sp = [2, 0, 3, 1, 4, 0]
parch = [1, 2, 1, 1, 2, 3]


In [9]:
# an approach, not using numpy
family_list = list(zip(sib_sp, parch))
family_list
[sum(family) + 1 for family in family_list]

[4, 3, 5, 3, 7, 4]

In [4]:
# numpy approach
sib_sp_np = np.array(sib_sp)
parch_np = np.array(parch)
family_size_np = parch_np + sib_sp_np + 1
family_size_np

array([4, 3, 5, 3, 7, 4])

**Exercise : BMI**

Calculate the BMI of these three people.  The BMI is the weight (kg) divided by the height (metres) squared.

In [23]:
weights = [74, 75, 76]
heights = [1.77, 1.76, 1.75]

In [24]:
w_np = np.array(weights)
h_np = np.array(heights)
def bmi(weight, height):
    """
    Returns the body mass index of a person given the weight (kg) and height(m) 
    """
    return weight / (height ** 2)

bmi(w_np, h_np)

array([23.62028791, 24.21229339, 24.81632653])

In [25]:
# Alternatively, we don't need to write a function for  to do this
weights_np = np.array(weights)
heights_np = np.array(heights)
weights_np / heights_np ** 2

array([23.62028791, 24.21229339, 24.81632653])


**Exercise: Football**

The numpy arrays below contain the results (the number of matches won, drawn and lost) of five teams.  For example the first team has won four matches, drawn two and lost one.  Teams have played a different number of matches.

1. Create a numpy array, team_played, to hold the number of games played 
2. Create a numpy array, team_score, to hold the teams scores (3 for a win, 1 for a draw, 0 for a loss)

In [26]:
team_won = np.array([4, 3, 1, 6, 3])
team_drawn = np.array([2, 1, 1, 7, 2])
team_lost = np.array([1, 3, 4, 5, 8])

In [27]:
# Total number of games played by each team
team_played = team_won + team_drawn + team_lost
team_played

array([ 7,  7,  6, 18, 13])

In [28]:
# Total number of points by each team
team_score = 3 * team_won + team_drawn
team_score

array([14, 10,  4, 25, 11])